version: "3.8"

services:
  mysql:
    image: mysql:8.0
    command: --local-infile=1 
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  
  importer:
    image: mysql:8.0
    depends_on:
      - mysql
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    entrypoint: ["bash", "/scripts/import.sh"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 100M
    ports:
      - "8080:80"
    depends_on:
      - mysql