version: "3.8"

services:
  mysql:
    image: mysql:8.0
    command: --local-infile=1 
    container_name: mysql-db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      # - ./db:/var/lib/mysq
    ports:
      - "3310:3306"
  redis:
    image: redis
    command: redis-server --requirepass Redis2019!
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "Redis2019!", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      REDIS_PASSWORD: Redis2019!
      HTTP_USER: root
      HTTP_PASSWORD: root
    ports:
      - 8081:8081
  
  importer:
    # image: mysql:8.0
    build: ./scripts
    depends_on:
      - mysql
      - redis
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    # entrypoint: ["bash", "/scripts/import.sh"]
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: Redis2019!
      BLOOM_BITSIZE: 48000000
      BLOOM_HASHCOUNT: 7
      BLOOM_REDIS_KEY: bloom:usuarios
      MYSQL_HOST: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: myDB

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 100M
    ports:
      - "8080:80"
    depends_on:
      - mysql
  
  api:
    build: ./api
    container_name: bloom-api
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3000:8000"

    environment:
      DB_PASSWORD: password
      DB_USER: user
      DB_HOST: mysql
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: Redis2019!

  # bloom-seeder:
  #   build: ./bloom-seeder
  #   depends_on:
  #     - mysql
  #     - redis
  #     - importer
  #   volumes:
  #     - ./data:/data
  #   environment:
      # MYSQL_HOST: mysql
      # MYSQL_USER: user
      # MYSQL_PASSWORD: password
      # MYSQL_DATABASE: myDB

      # REDIS_HOST: redis
      # REDIS_PORT: 6379
      # REDIS_PASSWORD: Redis2019!

      # BLOOM_BITSIZE: 48000000
      # BLOOM_HASHCOUNT: 7
      # BLOOM_REDIS_KEY: bloom:usuarios